### PR TITLE
Gen blocking

### PR DESCRIPTION
**Pull request by SuperFluffy**
Opening this PR to get your opinion if this is a valuable extension.

I am using dbus in a blocking context, and hence need to generate `*Blocking` types with `gen_blocking: true`. I opted to make this configurable through the config. To actually releases a crate that allows to toggle blocking proxies we could implement this in terms of a feature flag and `cfg_attr`, but I haven't looked into this.

### CODE REVIEW

**Comment by SuperFluffy** [comment]
I went ahead and regenerated the systemd bindings with `cfg_attr(feature = "blocking"` and `cfg_attr(not(feature = "blocking"`, respectively.

Unfortunately, `cfg_attr` is not expanded before being passed to the `dbus_proxy` proc macro, so something like the code below wouldn't work and we end up with essentially duplicating the entire `dbus_proxy` block. :-/

```rust
#[dbus_proxy(
    cfg_attr(feature = "blocking", gen_blocking = true,)
    cfg_attr(not(feature = "blocking"), gen_blocking = false,)
)]
```

**Comment by lucab** [comment]
Thanks for the PR.
I'll be honest, I'm not planning to also generate blocking helpers for the whole API surface, but sticking to async-only instead. I thought I had noted that in the motivations in the README but apparently I failed to do so, apologies for that.

The rationale are many, but overall DBus is an RPC system which pretty much always need some kind of multiplexing, canceling and timeouts. There may be some simpler projects with a need for blocking methods, but it's unlikely to span all of systemd API and in general it should be always possible to build the blocking logic on top of the async primitives provided here.

That said, I'm open to hear more about your blocking context. Likely it could be bridged to async with something simple like https://docs.rs/futures/latest/futures/executor/fn.block_on.html.

**Comment by SuperFluffy** [comment]
Using blocking methods (non async) was a deliberate choice for an updating system that is intended to be strictly sequential and single-threaded (this

I'm of course aware that I could restructure the

**Comment by lucab** [comment]
I can confirm my own previous comment, it is better to keep this crate to its current async-only surface.
There are many caveats in doing a sync-async sandwich (already noted at https://docs.rs/zbus/4.1.2/zbus/blocking/index.html), and I want to leave the decisions and their implications to the consumers.

I'm thus closing this PR, but thanks for your feedback.

**Comment by lucab** [comment]
Not really, and to be honest the technical summary above is not going to change over time:
> The rationale are many, but overall DBus is an RPC system which pretty much always need some kind of multiplexing, canceling or timeouts. There may be some simpler projects with a need for blocking methods, but it's unlikely to span all of systemd API and in general it should be always possible to build the blocking logic on top of the async primitives provided here.

Even in a simpler project which doesn't need multiplexing or concurrency, there are still timeouts and canceling concerns which need to be covered (or they'll eventually bite you into a deadlock).

So no, I plan for this crate to stay async for the foreseeable future, but I need to document this a bit more explicitly.

**Pull request closed without merging**
